### ISSUE TITLE
Tree-based intersection detection

### ISSUE THREAD

**Issue by dy** [anvaka/isect#1]
Hi @anvaka! Thanks for the awesome package.
That is also possible to implement intersection algorithm based on r-tree, as it is done here:
https://github.com/mclaeysb/geojson-polygon-self-intersections

That promises O(n*logn) complexity.

Just wonder is you would be interested in that.

**Comment by dy** [comment]
Rings are so-called polygons there, or collections of segments. Basically these ring-edge loops are just segments loops, which is O(n). But the tree search used inside the loop is O(log n), because tree clusters rectangles, it does not iterate over all of them.

**Comment by arendvw** [comment]
@avanka rtrees indeed use boundingboxes, and your examples could indeed have horrible performance. But for maps (their use case) overlapping boundingboxes would be the exception rather than the rule.

**Comment by district10** [comment]
Based on this idea (and rbush code), I release a python pip package [fast-crossing](https://fast-crossing.readthedocs.io/)

And added extra interface to expose intersected 3D point (one intersection, two points) to satisfy my typical use cases.
