### ISSUE TITLE
isect/brute, isect/sweep, isect/bush entries

### ISSUE THREAD

**Issue by dy** [anvaka/isect#2]
Thanks for the incredible work @anvaka!

That would be nice to have separate file entries for each algorithm, to reduce amount of bundled code and simplify API:

```js
import isect from "isect/brute"
isect(options)

//or
require("isect/bush")(data)
```

Just suggestion.

**Comment by anvaka** [comment]
Thank you for suggestion! I published under `v3.0.0` new API. Please let me know if this works for you
